application: coderbotsrv
version: 1
runtime: python27
api_version: 1
threadsafe: yes

automatic_scaling:
  min_idle_instances: 1
  max_pending_latency: 10s

skip_files:
- ^(.*/)?.*\.py[co]$
- .DS_Store

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: 2.6
- name: lxml
  version: 2.3
- name: pycrypto
  version: 2.6

handlers:
- url: /static
  static_dir: static

- url: /auth/.*
  script: auth.app

- url: /api/.*
  script: api.app

- url: .*
  script: main.app
